create table prices (
                       id bigint generated by default as identity,
                       currency varchar(3) not null,
                       end_date timestamp(6) with time zone not null,
                       price numeric(38,2) not null,
                       price_list integer,
                       priority bigint not null,
                       product_id bigint not null,
                       start_date timestamp(6) with time zone not null,
                       brand_id bigint not null,
                       primary key (id)
)